name: PlayerSQL
main: com.mengcraft.PlayerSQL.PlayerSQL
version: 0.6.4
commands:
    player:
        description:
        usage: 
        permission: playersql.admin
        permission-message:
permissions:
    playersql.admin:
        description: 
        default: op