name: PlayerSQL
main: com.mengcraft.playersql.PMain
version: 0.6.9
commands:
    player:
        permission: playersql.admin
permissions:
    playersql.admin:
        default: op
depend: [ProtocolLib]